apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
{{- toYaml .Values.labels | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  {{- if .Values.timeZone }}
  timeZone: {{ .Values.timeZone | quote }}
  {{- end }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 45
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 55
      template:
        metadata:
          labels:
{{- toYaml .Values.labels | nindent 12 }}
        spec:
          restartPolicy: Never
          terminationGracePeriodSeconds: 10
          containers:
            - name: data-handler
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
{{- toYaml .Values.resources | nindent 16 }}
