package com.trinity.hermes.indicators.tram.controller;

import com.trinity.hermes.common.logging.LogSanitizer;
import com.trinity.hermes.indicators.tram.dto.*;
import com.trinity.hermes.indicators.tram.facade.TramFacade;
import com.trinity.hermes.recommendation.dto.RecommendationResponse;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequiredArgsConstructor
@Slf4j
@CrossOrigin(origins = "*")
public class TramController {

  private final TramFacade tramFacade;

  /** Station list — under /api/v1/dashboard for frontend compatibility. */
  @GetMapping("/api/v1/dashboard/tram")
  public ResponseEntity<Map<String, Object>> getTramData(
      @RequestParam(defaultValue = "200") Integer limit) {
    log.info("Dashboard API: Getting tram data with limit: {}", LogSanitizer.sanitizeLog(limit));
    try {
      List<TramStopDTO> stops = tramFacade.getStops(limit);
      Map<String, Object> response = new HashMap<>();
      response.put("indicatorType", "tram");
      response.put("totalRecords", stops.size());
      response.put("data", stops);
      return ResponseEntity.ok(response);
    } catch (Exception e) {
      log.error("Error fetching tram data: {}", e.getMessage(), e);
      return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
    }
  }

  @GetMapping("/api/v1/tram/kpis")
  public ResponseEntity<TramKpiDTO> getKpis() {
    log.info("GET /api/v1/tram/kpis");
    return ResponseEntity.ok(tramFacade.getKpis());
  }

  @GetMapping("/api/v1/tram/live-forecasts")
  public ResponseEntity<List<TramLiveForecastDTO>> getLiveForecasts() {
    log.info("GET /api/v1/tram/live-forecasts");
    return ResponseEntity.ok(tramFacade.getLiveForecasts());
  }

  @GetMapping("/api/v1/tram/alternative-routes")
  public ResponseEntity<List<TramAlternativeRouteDTO>> getAlternativeRoutes(
      @RequestParam String stopId) {
    log.info("GET /api/v1/tram/alternative-routes");
    return ResponseEntity.ok(tramFacade.getAlternativeRoutes(stopId));
  }

  @GetMapping("/api/v1/tram/delays")
  public ResponseEntity<List<TramDelayDTO>> getDelays() {
    log.info("GET /api/v1/tram/delays");
    return ResponseEntity.ok(tramFacade.getDelays());
  }

  @GetMapping("/api/v1/tram/hourly-distribution")
  public ResponseEntity<List<TramHourlyDistributionDTO>> getHourlyDistribution() {
    log.info("GET /api/v1/tram/hourly-distribution");
    return ResponseEntity.ok(tramFacade.getHourlyDistribution());
  }

  /** Per-stop estimated passenger usage for a time period. */
  @GetMapping("/api/v1/tram/stop-usage")
  public ResponseEntity<List<TramStopUsageDTO>> getStopUsage(
      @RequestParam(defaultValue = "7") int startHour,
      @RequestParam(defaultValue = "10") int endHour) {
    log.info("GET /api/v1/tram/stop-usage?startHour={}&endHour={}", startHour, endHour);
    return ResponseEntity.ok(tramFacade.getStopUsage(startHour, endHour));
  }

  /** Historical average delay per stop. */
  @GetMapping("/api/v1/tram/common-delays")
  public ResponseEntity<List<TramCommonDelayDTO>> getCommonDelays() {
    log.info("GET /api/v1/tram/common-delays");
    return ResponseEntity.ok(tramFacade.getCommonDelays());
  }

  /** Demand score per stop — utilisation for a given time period. */
  @GetMapping("/api/v1/tram/stop-demand")
  public ResponseEntity<List<TramStopDemandDTO>> getStopDemand(
      @RequestParam(defaultValue = "7") int startHour,
      @RequestParam(defaultValue = "10") int endHour) {
    log.info("GET /api/v1/tram/stop-demand?startHour={}&endHour={}", startHour, endHour);
    try {
      return ResponseEntity.ok(tramFacade.getStopDemand(startHour, endHour));
    } catch (Exception e) {
      log.error("Error fetching tram stop demand: {}", e.getMessage(), e);
      return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
    }
  }

  /** Simulate adding/removing trams and return updated demand scores. */
  @PostMapping("/api/v1/tram/stop-demand/simulate")
  public ResponseEntity<TramDemandSimulateResponseDTO> simulateDemand(
      @RequestBody TramDemandSimulateRequestDTO request) {
    log.info(
        "POST /api/v1/tram/stop-demand/simulate line={} extraTrams={} startHour={} endHour={}",
        request.getLine(),
        request.getExtraTrams(),
        request.getStartHour(),
        request.getEndHour());
    try {
      return ResponseEntity.ok(tramFacade.simulateDemand(request));
    } catch (Exception e) {
      log.error("Error simulating tram demand: {}", e.getMessage(), e);
      return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
    }
  }

  /** Service change recommendations generated by the inference engine. */
  @GetMapping("/api/v1/tram/recommendations")
  public ResponseEntity<List<RecommendationResponse>> getRecommendations() {
    log.info("GET /api/v1/tram/recommendations");
    return ResponseEntity.ok(tramFacade.getRecommendations());
  }
}
