apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"dev-allow-postgres-egress","namespace":"dev"},"spec":{"egress":[{"ports":[{"port":5432,"protocol":"TCP"}],"to":[{"podSelector":{"matchLabels":{"app.kubernetes.io/instance":"sec","app.kubernetes.io/name":"postgresql"}}}]}],"podSelector":{},"policyTypes":["Egress"]}}
  creationTimestamp: "2026-01-30T14:39:57Z"
  generation: 1
  name: dev-allow-postgres-egress
  namespace: dev
  resourceVersion: "1769783997396271015"
  uid: 6a8a4f65-6c63-4f0f-b420-56a0bb9248fa
spec:
  egress:
  - ports:
    - port: 5432
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: sec
          app.kubernetes.io/name: postgresql
  podSelector: {}
  policyTypes:
  - Egress
