{{- $existingRootSecret := lookup "v1" "Secret" .Release.Namespace "sec-db-root" -}}
{{- $existingDataHandlerUserSecret := lookup "v1" "Secret" .Release.Namespace "sec-db-data-handler-user" -}}
{{- $existingPostgresPassword := "" -}}
{{- $existingAppOwnerPassword := "" -}}
{{- $existingDataHandlerPassword := "" -}}
{{- if and $existingRootSecret $existingRootSecret.data (index $existingRootSecret.data "postgres-password") -}}
  {{- $existingPostgresPassword = index $existingRootSecret.data "postgres-password" | b64dec -}}
{{- end -}}
{{- if and $existingRootSecret $existingRootSecret.data (index $existingRootSecret.data "password") -}}
  {{- $existingAppOwnerPassword = index $existingRootSecret.data "password" | b64dec -}}
{{- end -}}
{{- if and $existingDataHandlerUserSecret $existingDataHandlerUserSecret.data (index $existingDataHandlerUserSecret.data "DB_DATA_HANDLER_PASSWORD") -}}
  {{- $existingDataHandlerPassword = index $existingDataHandlerUserSecret.data "DB_DATA_HANDLER_PASSWORD" | b64dec -}}
{{- end -}}
{{- $postgresPassword := .Values.db.root.postgresPassword | default $existingPostgresPassword | default (randAlphaNum 32) -}}
{{- $appOwnerPassword := .Values.db.root.appOwnerPassword | default $existingAppOwnerPassword | default (randAlphaNum 32) -}}
{{- $dataHandlerPassword := .Values.db.users.dataHandlerPassword | default $existingDataHandlerPassword | default (randAlphaNum 32) -}}

apiVersion: v1
kind: Secret
metadata:
  name: sec-db-root
type: Opaque
stringData:
  postgres-password: {{ $postgresPassword | quote }}
  password: {{ $appOwnerPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sec-db-data-handler-user
type: Opaque
stringData:
  DB_DATA_HANDLER_USER: "data_handler"
  DB_DATA_HANDLER_PASSWORD: {{ $dataHandlerPassword | quote }}
