{{- $existingKeycloakAdminSecret := lookup "v1" "Secret" .Release.Namespace "sec-keycloak-admin" -}}
{{- $existingKeycloakAdminPassword := "" -}}
{{- if and $existingKeycloakAdminSecret $existingKeycloakAdminSecret.data (index $existingKeycloakAdminSecret.data "KEYCLOAK_ADMIN_PASSWORD") -}}
  {{- $existingKeycloakAdminPassword = index $existingKeycloakAdminSecret.data "KEYCLOAK_ADMIN_PASSWORD" | b64dec -}}
{{- end -}}
{{- $keycloakAdminPassword := .Values.keycloak.auth.adminUserPassword | default $existingKeycloakAdminPassword | default (randAlphaNum 32) -}}

apiVersion: v1
kind: Secret
metadata:
  name: sec-keycloak-admin
type: Opaque
stringData:
  KEYCLOAK_ADMIN_PASSWORD: {{ $keycloakAdminPassword | quote }}
---
{{- if .Values.keycloak.realm.enabled }}
{{- $existingRealmSecret := lookup "v1" "Secret" .Release.Namespace "sec-keycloak-realm" -}}
{{- $existingUserServiceClientSecret := "" -}}
{{- if and $existingRealmSecret $existingRealmSecret.data (index $existingRealmSecret.data "USER_SERVICE_CLIENT_SECRET") -}}
  {{- $existingUserServiceClientSecret = index $existingRealmSecret.data "USER_SERVICE_CLIENT_SECRET" | b64dec -}}
{{- end -}}
{{- $userServiceClientSecret := .Values.keycloak.realm.userServiceClientSecret | default $existingUserServiceClientSecret -}}
{{- if not $userServiceClientSecret -}}
  {{- fail "keycloak.realm.userServiceClientSecret must be set in values.yaml" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: sec-keycloak-realm
type: Opaque
stringData:
  USER_SERVICE_CLIENT_SECRET: {{ $userServiceClientSecret | quote }}
{{- end }}
