package com.trinity.hermes.indicators.cycle.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Log of every rebalancing suggestion generated by the system. One row per suggestion per capture
 * run. Gives the inference engine a historical record of supply-demand gaps so it can learn when
 * and where shortages recur.
 */
@Entity
@Table(name = "cycle_rebalancing_log", schema = "backend")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class CycleRebalancingLog {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /** When this suggestion was captured. */
  @Column(name = "logged_at", nullable = false)
  private Instant loggedAt;

  /** Rank within this capture run (1 = most urgent). */
  @Column(name = "priority_rank")
  private Integer priorityRank;

  // ── Source (full station — needs bikes moved out) ──────────────────────────

  @Column(name = "source_station_id", nullable = false)
  private Integer sourceStationId;

  @Column(name = "source_name")
  private String sourceName;

  @Column(name = "source_bikes")
  private Integer sourceBikes;

  // ── Target (empty station — needs bikes moved in) ──────────────────────────

  @Column(name = "target_station_id", nullable = false)
  private Integer targetStationId;

  @Column(name = "target_name")
  private String targetName;

  @Column(name = "target_capacity")
  private Integer targetCapacity;

  /** Straight-line distance in kilometres between source and target. */
  @Column(name = "distance_km")
  private Double distanceKm;
}
