apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"allow-nginx-to-certmanager-http01","namespace":"dev"},"spec":{"ingress":[{"from":[{"namespaceSelector":{"matchLabels":{"kubernetes.io/metadata.name":"ingress"}}}],"ports":[{"port":8089,"protocol":"TCP"}]}],"podSelector":{"matchLabels":{"acme.cert-manager.io/http01-solver":"true"}},"policyTypes":["Ingress"]}}
  creationTimestamp: "2026-01-31T15:05:39Z"
  generation: 2
  name: allow-nginx-to-certmanager-http01
  namespace: dev
  resourceVersion: "1769871986369103014"
  uid: a88ef707-d8ae-494e-ae9f-20f19b29b4d7
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress
    ports:
    - port: 8089
      protocol: TCP
  podSelector:
    matchLabels:
      acme.cert-manager.io/http01-solver: "true"
  policyTypes:
  - Ingress
