apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"dev-allow-egress-to-hermes","namespace":"dev"},"spec":{"egress":[{"ports":[{"port":8080,"protocol":"TCP"}],"to":[{"podSelector":{"matchLabels":{"app.kubernetes.io/instance":"sec","app.kubernetes.io/name":"hermes"}}}]}],"podSelector":{},"policyTypes":["Egress"]}}
  creationTimestamp: "2026-01-30T21:33:59Z"
  generation: 1
  name: dev-allow-egress-to-hermes
  namespace: dev
  resourceVersion: "1769808839265631007"
  uid: fd95ba42-2e47-4ba3-b7c3-9ec2c903185b
spec:
  egress:
  - ports:
    - port: 8080
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: sec
          app.kubernetes.io/name: hermes
  podSelector: {}
  policyTypes:
  - Egress
