apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"dev-allow-egress-to-keycloak","namespace":"dev"},"spec":{"egress":[{"ports":[{"port":8080,"protocol":"TCP"}],"to":[{"podSelector":{"matchLabels":{"app.kubernetes.io/instance":"sec","app.kubernetes.io/name":"keycloak"}}}]}],"podSelector":{},"policyTypes":["Egress"]}}
  creationTimestamp: "2026-01-30T22:35:14Z"
  generation: 1
  name: dev-allow-egress-to-keycloak
  namespace: dev
  resourceVersion: "1769812514509503003"
  uid: cee451c8-85e0-406c-888f-3d166e243069
spec:
  egress:
  - ports:
    - port: 8080
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: sec
          app.kubernetes.io/name: keycloak
  podSelector: {}
  policyTypes:
  - Egress
