apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-namespace-admin
  namespace: dev
rules:
- apiGroups: ["", "apps", "batch", "autoscaling", "networking.k8s.io"]
  resources:
    - pods
    - pods/log
    - pods/exec
    - services
    - endpoints
    - configmaps
    - secrets
    - persistentvolumeclaims
    - deployments
    - replicasets
    - statefulsets
    - daemonsets
    - jobs
    - cronjobs
    - horizontalpodautoscalers
    - ingresses
  verbs: ["get","list","watch","create","update","patch","delete"]
